-- ============================================================
-- SUPABASE DATABASE & STORAGE SCHEMA FOR ZOOMER IMPEX
-- ============================================================

-- 1. Create zoomer_settings table
CREATE TABLE IF NOT EXISTS public.zoomer_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on zoomer_settings
ALTER TABLE public.zoomer_settings ENABLE ROW LEVEL SECURITY;

-- Allow public read access to settings
CREATE POLICY "Allow public read access on settings" 
ON public.zoomer_settings FOR SELECT USING (true);

-- Allow public insert/update on settings
CREATE POLICY "Allow public write access on settings" 
ON public.zoomer_settings FOR ALL USING (true);

-- 2. Create zoomer_contacts table
CREATE TABLE IF NOT EXISTS public.zoomer_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company_name TEXT,
    email TEXT NOT NULL,
    phone TEXT,
    subject TEXT,
    message TEXT,
    status TEXT DEFAULT 'new'::text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on zoomer_contacts
ALTER TABLE public.zoomer_contacts ENABLE ROW LEVEL SECURITY;

-- Allow public to submit contact messages
CREATE POLICY "Allow public contact submission" 
ON public.zoomer_contacts FOR INSERT WITH CHECK (true);

-- Allow public read/update access for admin dashboard
CREATE POLICY "Allow admin read contacts" 
ON public.zoomer_contacts FOR SELECT USING (true);

CREATE POLICY "Allow admin update contacts" 
ON public.zoomer_contacts FOR UPDATE USING (true);

-- 3. Create zoomer_admins table
CREATE TABLE IF NOT EXISTS public.zoomer_admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on zoomer_admins
ALTER TABLE public.zoomer_admins ENABLE ROW LEVEL SECURITY;

-- Allow public select for admin login validation
CREATE POLICY "Allow admin login query" 
ON public.zoomer_admins FOR SELECT USING (true);

-- Insert default admin account (username: admin, password: password123)
INSERT INTO public.zoomer_admins (username, password_hash) 
VALUES ('admin', 'password123')
ON CONFLICT (username) DO NOTHING;

-- 4. Insert Default Page Settings & Storage Image URLs into zoomer_settings
INSERT INTO public.zoomer_settings (key, value) VALUES
('topbar_email', 'zoomerimpex@gmail.com'),
('topbar_phone', '+91 86088 40943'),
('nav_subtitle', 'Kids Wear Manufacturer & Exporter'),
('hero_eyebrow', 'PREMIUM KIDS FASHION'),
('hero_title', 'Crafting Smiles with Every Stitch'),
('hero_subtitle', 'Leading exporter of comfortable, trendy & high-quality kids garments worldwide.'),
('hero_brand', 'ZOOMER'),
('hero_tagline', 'SMILES WITH EVERY STITCH'),
('hero_badge', '100% Cotton'),
('about_title', 'Passionate About Quality Kids Wear'),
('about_p1', 'Zoomer Impex has been a trusted name in kids apparel manufacturing for over a decade. We specialize in producing premium cotton dresses, frocks, casual wear, and custom collections for global brands.'),
('about_p2', 'Our state-of-the-art production facilities and strict quality standards ensure that every piece of clothing is safe, soft, durable, and stylish for children of all ages.'),
('stat_styles', '500+'),
('stat_clients', '120+'),
('stat_countries', '15+'),
('stat_years', '10+'),
('stat_quality', '100%'),
('contact_address', '123 Textile Avenue, Garment Hub, Tirupur, Tamil Nadu 641601'),
('contact_email', 'zoomerimpex@gmail.com'),
('contact_phone', '+91 86088 40943'),
('contact_website', 'www.zoomerimpex.com'),
('footer_copy', '© 2026 Zoomer Impex. All rights reserved.'),
-- Image URLs stored in database / Supabase storage
('img_hero', 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'),
('img_about', 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80'),
('img_phero', 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?auto=format&fit=crop&w=1200&q=80'),
('img_p1', 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=500&q=80'),
('img_p2', 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=500&q=80'),
('img_p3', 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=500&q=80'),
('img_p4', 'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?auto=format&fit=crop&w=500&q=80'),
('img_p5', 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=500&q=80'),
('img_bhero', 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'),
('img_bpromise', 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?auto=format&fit=crop&w=800&q=80'),
('img_bg1', 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=500&q=80'),
('img_bg2', 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=500&q=80'),
('img_bg3', 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=500&q=80'),
('img_bg4', 'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?auto=format&fit=crop&w=500&q=80'),
('img_why', 'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?auto=format&fit=crop&w=800&q=80'),
('img_quality', 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80'),
('img_contact', 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=80')
ON CONFLICT (key) DO NOTHING;

-- 5. Supabase Storage Bucket Setup for Product Images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('zoomer-assets', 'zoomer-assets', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Read Access for zoomer-assets" 
ON storage.objects FOR SELECT USING (bucket_id = 'zoomer-assets');

CREATE POLICY "Public Upload Access for zoomer-assets" 
ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'zoomer-assets');
